# Generated by Django 4.2.24 on 2025-09-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.datasource')),
            ],
            options={
                'unique_together': {('datasource', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='OHLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlc', to='app.stock')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='app_ohlc_stock_i_0b773d_idx')],
            },
        ),
    ]
