# Generated by Django 4.2.24 on 2025-09-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_datasource_id_alter_ohlc_id_alter_stock_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('name', 'type')},
        ),
    ]
